import type { ThemeContent } from "./types";

export const TEMA_01: ThemeContent = {
  id: 1,
  nivel: "N4",
  titulo: "Presentaciones y 〜てください (explicado como para primaria)",

  objetivos: [
    "Pedir cosas con 〜てください (por favor...).",
    "Pasar verbos: ます → diccionario → て usando una regla muy fácil.",
    "Reconocer verbos de Grupo 1, 2 y 3 con una regla corta.",
    "Usar A は B です y A は B ですか en presentaciones simples.",
  ],

  vocabClase: [
    { key: "w1", jp: "なまえ", romaji: "namae", es: "nombre" },
    { key: "w2", jp: "しゅっしん", romaji: "shusshin", es: "origen / lugar de procedencia" },
    { key: "w3", jp: "くに", romaji: "kuni", es: "país" },
    { key: "w4", jp: "ねんれい", romaji: "nenrei", es: "edad" },
    { key: "w5", jp: "しごと", romaji: "shigoto", es: "trabajo / ocupación" },
    { key: "w6", jp: "かいしゃ", romaji: "kaisha", es: "empresa" },
    { key: "w7", jp: "かいしゃいん", romaji: "kaishain", es: "empleado de empresa" },
    { key: "w8", jp: "がくせい", romaji: "gakusei", es: "estudiante" },
    { key: "w9", jp: "せんもん", romaji: "senmon", es: "especialidad" },
    { key: "w10", jp: "しゅみ", romaji: "shumi", es: "afición" },
  ],

  oraciones6: [
    { key: "s1", jp: "はじめまして。わたしはまりおです。",
      romaji: "hajimemashite. watashi wa mario desu.", es: "Mucho gusto. Yo soy Mario.", exp: "A は B です." },
    { key: "s2", jp: "おなまえをおしえてください。",
      romaji: "onamae o oshiete kudasai.", es: "Por favor, dígame su nombre.", exp: "て + ください." },
    { key: "s3", jp: "しゅっしんはどちらですか。",
      romaji: "shusshin wa dochira desu ka?", es: "¿De dónde es?", exp: "A は B ですか." },
    { key: "s4", jp: "しゅっしんはめきしこです。",
      romaji: "shusshin wa mekishiko desu.", es: "Mi origen es México.", exp: "A は B です." },
    { key: "s5", jp: "しごとはかいしゃいんです。",
      romaji: "shigoto wa kaishain desu.", es: "Mi trabajo es empleado de empresa.", exp: "Tema は + profesión です." },
    { key: "s6", jp: "ここをみてください。",
      romaji: "koko o mite kudasai.", es: "Por favor, mire aquí.", exp: "て + ください." },
  ],

  gramatica: {
    titulo: "Gramática (súper simple, estilo primaria)",
    puntos: [
      /* ========== 1) A は B です ========== */
      {
        regla: "A は B です (A es B)",
        pasoapaso: [
          "A = tema (de qué hablas).",
          "は (wa) marca el tema (se escribe は, se lee wa).",
          "B = lo que dices de A.",
          "です = es/soy/son (cortés).",
          "Usa esto para presentarte, decir profesión, país o gustos.",
          "7 oraciones:",
          "1) わたしは がくせい です。 — watashi wa gakusei desu. — Yo soy estudiante.",
          "2) まりおは かいしゃいん です。 — mario wa kaishain desu. — Mario es empleado.",
          "3) わたしの しゅみは えいが です。 — watashi no shumi wa eiga desu. — Mi afición es el cine.",
          "4) ここは こうこう です。 — koko wa koukou desu. — Aquí es la prepa.",
          "5) いまは にちようび です。 — ima wa nichiyoubi desu. — Hoy es domingo.",
          "6) これは ぺん です。 — kore wa pen desu. — Esto es una pluma.",
          "7) きょうは あつい です。 — kyou wa atsui desu. — Hoy hace calor.",
        ],
        ejemploJP: "わたし は がくせい です。",
        ejemploRoma: "watashi wa gakusei desu.",
        ejemploES: "Yo soy estudiante.",
      },

      /* ========== 2) A は B ですか ========== */
      {
        regla: "A は B ですか (¿A es B?)",
        pasoapaso: [
          "Para preguntar, pon か (ka) al final.",
          "Habla normal y sube un poco la voz al final.",
          "7 oraciones:",
          "1) おなまえは なん ですか。 — onamae wa nan desu ka? — ¿Cuál es su nombre?",
          "2) しゅっしんは どちら ですか。 — shusshin wa dochira desu ka? — ¿De dónde es?",
          "3) しごとは なん ですか。 — shigoto wa nan desu ka? — ¿Cuál es su trabajo?",
          "4) がくせい ですか。 — gakusei desu ka? — ¿Eres/Es estudiante?",
          "5) せんもんは なん ですか。 — senmon wa nan desu ka? — ¿Cuál es tu/su especialidad?",
          "6) これは ぺん ですか。 — kore wa pen desu ka? — ¿Esto es una pluma?",
          "7) あしたは やすみ ですか。 — ashita wa yasumi desu ka? — ¿Mañana es descanso?",
        ],
        ejemploJP: "しゅっしん は どちら です か。",
        ejemploRoma: "shusshin wa dochira desu ka?",
        ejemploES: "¿De dónde es?",
      },

      /* ========== 3) Reconocer grupos (tu regla fácil) ========== */
      {
        regla: "Verbos: grupos 1, 2 y 3 (regla fácil)",
        pasoapaso: [
          "1) Mira el verbo en ます.",
          "2) Borra ます (ej. かきます → かき).",
          "3) Si termina en “e” (…え) o tiene 1 vocal → Grupo 2.",
          "4) Si tiene 2 o más vocales y no termina en “e” → Grupo 1.",
          "5) Grupo 3 = de memoria: します → する, きます → くる.",
          "7 oraciones para mirar el grupo:",
          "1) たべる。 — taberu. — Comer. (G2)",
          "2) みる。 — miru. — Mirar. (G2)",
          "3) する。 — suru. — Hacer. (G3)",
          "4) くる。 — kuru. — Venir. (G3)",
          "5) よむ。 — yomu. — Leer. (G1)",
          "6) かく。 — kaku. — Escribir/dibujar. (G1)",
          "7) はなす。 — hanasu. — Hablar. (G1)",
        ],
        ejemploJP: "たべます → たべ (termina en e) → G2",
        ejemploRoma: "tabemasu → tabe → G2",
        ejemploES: "Guíate por la vocal final y cuántas vocales hay.",
      },

      /* ========== 4) ます → diccionario (con TABLA) ========== */
      {
        regla: "Pasos: ます → diccionario (con tabla)",
        pasoapaso: [
          "Usa la regla de grupos de arriba.",
          "G2: quita ます y añade る (たべます→たべる, みます→みる, あけます→あける).",
          "G3: します→する, きます→くる.",
          "G1: cambia a la forma diccionario (ej. かきます→かく, よみます→よむ).",
          "Luego ya puedes usar esa forma para otras reglas.",
          "7 oraciones usando diccionario:",
          "1) にっきを かく。 — nikki o kaku. — Escribo diario.",
          "2) みずを のむ。 — mizu o nomu. — Bebo agua.",
          "3) えいがを みる。 — eiga o miru. — Miro película.",
          "4) おんがくを きく。 — ongaku o kiku. — Escucho música.",
          "5) ごはんを たべる。 — gohan o taberu. — Como.",
          "6) しゅくだいを する。 — shukudai o suru. — Hago tarea.",
          "7) あした がっこうへ くる。 — ashita gakkou e kuru. — Mañana vengo a la escuela.",
        ],
        ejemploJP: "のみます → のみ → のむ",
        ejemploRoma: "nomimasu → nomi → nomu",
        ejemploES: "De ます a diccionario.",
        tabla: {
          title: "Tabla 1 — ます → diccionario (regla fácil aplicada)",
          headers: ["masu", "sin masu", "vocales", "termina e", "grupo", "diccionario"],
          rows: [
            ["かきます", "かき", "2", "no", "G1", "かく (kaku)"],
            ["はなします", "はなし", "3", "no", "G1", "はなす (hanasu)"],
            ["よみます", "よみ", "2", "no", "G1", "よむ (yomu)"],
            ["のみます", "のみ", "2", "no", "G1", "のむ (nomu)"],
            ["まちます", "まち", "2", "no", "G1", "まつ (matsu)"],
            ["あけます", "あけ", "2", "sí", "G2", "あける (akeru)"],
            ["みせます", "みせ", "2", "sí", "G2", "みせる (miseru)"],
            ["おしえます", "おしえ", "3", "sí", "G2", "おしえる (oshieru)"],
            ["たべます", "たべ", "2", "sí", "G2", "たべる (taberu)"],
            ["みます", "み", "1", "no", "G2", "みる (miru)"],
            ["します", "し", "1", "no", "G3", "する (suru)"],
            ["きます", "き", "1", "no", "G3", "くる (kuru)"],
          ],
          note: "‘vocales’ cuenta vocales en la parte sin ます. Si termina en ‘e’ (…え) o tiene 1 vocal → G2. Si tiene 2+ vocales y no termina en ‘e’ → G1. G3 se memoriza."
        },
      },

      /* ========== 5) diccionario → て (con TABLA) ========== */
      {
        regla: "Pasos: diccionario → て (con tabla)",
        pasoapaso: [
          "G2: る → て  (たべる→たべて, みる→みて).",
          "G3: する→して, くる→きて.",
          "G1 (mira la última letra):",
          " う / つ / る → って",
          " む / ぶ / ぬ → んで",
          " く → いて（※ いく → いって）",
          " ぐ → いで",
          " す → して",
          "7 oraciones con forma て:",
          "1) まどを あけて。 — mado o akete. — Abre la ventana.",
          "2) ほんを よんで。 — hon o yonde. — Lee el libro.",
          "3) ごはんを たべて。 — gohan o tabete. — Come.",
          "4) なまえを かいて。 — namae o kaite. — Escribe tu nombre.",
          "5) てを あらって。 — te o aratte. — Lava las manos.",
          "6) せんせいに きいて。 — sensei ni kiite. — Pregunta al profe.",
          "7) はやく きて。 — hayaku kite. — Ven rápido.",
        ],
        ejemploJP: "かく → かいて / たべる → たべて / する → して",
        ejemploRoma: "kaku → kaite / taberu → tabete / suru → shite",
        ejemploES: "De diccionario a て.",
        tabla: {
          title: "Tabla 2 — diccionario → て",
          headers: ["diccionario", "regla", "forma て", "ejemplo 〜てください"],
          rows: [
            ["かく", "く→いて", "かいて", "なまえを かいて ください。"],
            ["はなす", "す→して", "はなして", "しずかに はなして ください。"],
            ["よむ", "む→んで", "よんで", "ほんを よんで ください。"],
            ["のむ", "む→んで", "のんで", "みずを のんで ください。"],
            ["まつ", "つ→って", "まって", "ここで まって ください。"],
            ["あける", "る→て (G2)", "あけて", "まどを あけて ください。"],
            ["みせる", "る→て (G2)", "みせて", "しゅくだいを みせて ください。"],
            ["おしえる", "る→て (G2)", "おしえて", "もういちど おしえて ください。"],
            ["たべる", "る→て (G2)", "たべて", "ゆっくり たべて ください。"],
            ["みる", "る→て (G2)", "みて", "ここを みて ください。"],
            ["する", "irregular", "して", "しずかに して ください。"],
            ["くる", "irregular", "きて", "はやく きて ください。"],
            ["いく", "※ いく→いって", "いって", "もういちど いって ください。"],
          ],
          note: "Recuerda: いく es excepción → いって."
        },
      },

      /* ========== 6) 〜てください ========== */
      {
        regla: "〜てください (por favor...)",
        pasoapaso: [
          "Cómo se hace:",
          "1) Verbo (ます) → pasa a diccionario.",
          "2) Diccionario → pasa a て.",
          "3) Añade ください: 〜て ください.",
          "Ejemplo: たべます → たべる → たべて → たべて ください.",
          "7 oraciones:",
          "1) すわって ください。 — suwatte kudasai. — Por favor, siéntate/siéntese.",
          "2) たって ください。 — tatte kudasai. — Por favor, ponte/póngase de pie.",
          "3) しずかに して ください。 — shizuka ni shite kudasai. — Por favor, guarda silencio.",
          "4) ここを みて ください。 — koko o mite kudasai. — Por favor, mire aquí.",
          "5) もういちど いって ください。 — mou ichido itte kudasai. — Repite una vez más, por favor.",
          "6) でんきを けして ください。 — denki o keshite kudasai. — Por favor, apaga la luz.",
          "7) はやく きて ください。 — hayaku kite kudasai. — Por favor, ven pronto.",
        ],
        ejemploJP: "おしえて ください。",
        ejemploRoma: "oshiete kudasai.",
        ejemploES: "Por favor, enséñeme / dígame.",
      },
    ],
  },

  /* ===== Diálogos: SIN KANJI (ambos campos con kana) ===== */
  dialogos: [
    {
      title: "だいやろぐ 1 — じこしょうかい",
      kana: [
        "A: はじめまして。わたしはまりおです。",
        "B: はじめまして。わたしはたなかです。",
        "A: おなまえはなんですか。",
        "B: たなかです。よろしくおねがいします。",
      ],
      kanji: [
        "A: はじめまして。わたしはまりおです。",
        "B: はじめまして。わたしはたなかです。",
        "A: おなまえはなんですか。",
        "B: たなかです。よろしくおねがいします.",
      ],
      es: [
        "A: Mucho gusto. Soy Mario.",
        "B: Mucho gusto. Soy Tanaka.",
        "A: ¿Cuál es su nombre?",
        "B: Soy Tanaka. Mucho gusto.",
      ],
    },
    {
      title: "だいやろぐ 2 — くに と しごと",
      kana: [
        "A: しゅっしんのくにはどこですか。",
        "B: くにはめきしこです。",
        "A: しごとはなんですか。",
        "B: かいしゃいんです。",
      ],
      kanji: [
        "A: しゅっしんのくにはどこですか。",
        "B: くにはめきしこです。",
        "A: しごとはなんですか。",
        "B: かいしゃいんです。",
      ],
      es: [
        "A: ¿De qué país eres/es?",
        "B: Mi país es México.",
        "A: ¿Cuál es tu/su trabajo?",
        "B: Soy empleado de empresa.",
      ],
    },
    {
      title: "だいやろぐ 3 — 〜てください",
      kana: [
        "A: すわってください。",
        "B: はい、すわります。",
        "A: ここをみてください。",
        "B: はい、みます。",
      ],
      kanji: [
        "A: すわってください。",
        "B: はい、すわります。",
        "A: ここをみてください。",
        "B: はい、みます。",
      ],
      es: [
        "A: Por favor, siéntese/siéntate.",
        "B: Sí, me siento.",
        "A: Por favor, mire aquí.",
        "B: Sí, miro.",
      ],
    },
  ],

  /* Mini-práctica corta sin kanji */
  quizLines: [
    "A: しゅっしんのくにはどこですか。",
    "B: くにはめきしこです。",
    "A: しごとはなんですか。",
    "B: かいしゃいんです。",
  ],

  /* Esta sección sí usa kanji por diseño del curso (estudio de kanji) */
  kanji10: [
    { ch: "私", kun: ["わたし"], on: ["シ"], es: "yo",
      ej: [ { jp: "私は学生です。", yomi: "わたしはがくせいです。", es: "Yo soy estudiante." },
            { jp: "私はかいしゃいんです。", yomi: "わたしはかいしゃいんです。", es: "Yo soy empleado de empresa." } ],
      strokeCode: "79c1" },
    { ch: "名", kun: ["な"], on: ["メイ"], es: "nombre",
      ej: [ { jp: "お名前はなんですか。", yomi: "おなまえはなんですか。", es: "¿Cuál es su nombre?" },
            { jp: "名前はまりおです。", yomi: "なまえはまりおです。", es: "Mi nombre es Mario." } ],
      strokeCode: "540d" },
    { ch: "前", kun: ["まえ"], on: ["ゼン"], es: "antes / frente",
      ej: [ { jp: "前のしごとはなんですか。", yomi: "まえのしごとはなんですか。", es: "¿Cuál es el trabajo anterior?" },
            { jp: "前はがくせいでした。", yomi: "まえはがくせいでした。", es: "Antes era estudiante." } ],
      strokeCode: "524d" },
    { ch: "国", kun: ["くに"], on: ["コク"], es: "país",
      ej: [ { jp: "国はメキシコです。", yomi: "くにはめきしこです。", es: "Mi país es México." },
            { jp: "国はどこですか。", yomi: "くにはどこですか。", es: "¿Cuál es su país?" } ],
      strokeCode: "56fd" },
    { ch: "学", kun: ["まな-ぶ"], on: ["ガク"], es: "estudiar",
      ej: [ { jp: "学生です。", yomi: "がくせいです。", es: "Soy estudiante." },
            { jp: "学生ですか。", yomi: "がくせいですか。", es: "¿Es estudiante?" } ],
      strokeCode: "5b66" },
    { ch: "生", kun: ["い-きる","う-まれる"], on: ["セイ"], es: "vida / nacer",
      ej: [ { jp: "学生です。", yomi: "がくせいです。", es: "Soy estudiante." },
            { jp: "学生ですか。", yomi: "がくせいですか。", es: "¿Es estudiante?" } ],
      strokeCode: "751f" },
    { ch: "社", kun: [], on: ["シャ"], es: "compañía",
      ej: [ { jp: "会社です。", yomi: "かいしゃです。", es: "Es una empresa." },
            { jp: "会社ですか。", yomi: "かいしゃですか。", es: "¿Es una empresa?" } ],
      strokeCode: "793e" },
    { ch: "員", kun: [], on: ["イン"], es: "miembro / empleado",
      ej: [ { jp: "会社員です。", yomi: "かいしゃいんです。", es: "Soy empleado de empresa." },
            { jp: "会社員ですか。", yomi: "かいしゃいんですか。", es: "¿Es empleado de empresa?" } ],
      strokeCode: "54e1" },
    { ch: "仕", kun: [], on: ["シ"], es: "servir / hacer",
      ej: [ { jp: "仕事です。", yomi: "しごとです。", es: "Es trabajo." },
            { jp: "仕事はなんですか。", yomi: "しごとはなんですか。", es: "¿Cuál es el trabajo?" } ],
      strokeCode: "4ed5" },
    { ch: "事", kun: ["こと"], on: ["ジ"], es: "cosa / asunto / trabajo",
      ej: [ { jp: "仕事の事です。", yomi: "しごとのことです。", es: "Es sobre el trabajo." } ],
      strokeCode: "4e8b" },
  ],
};

export default TEMA_01;
